### ISSUE TITLE
clone hangs

### ISSUE THREAD

**Issue by whit2333** [cjb/GitTorrent#8]
Here is the debug output: 

```bash
$ DEBUG=* git clone gittorrent://github.com/cjb/gittorrent

Cloning into 'gittorrent'...
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] new DHT d7fe598df94d12af9477db69aed2f12ab096464a
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] bootstrap with ["dht.gittorrent.org:6881","core.gittorrent.org:6881"]
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] listen undefined
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] emit listening 41222
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] lookup (find_node) d7fe598df94d12af9477db69aed2f12ab096464a
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 192.34.86.38:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode e2d7c060225f930c31dc1bf7462ad09ac6ca466c 192.34.86.36:6881 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] skip addNode 73.168.2.221:41222 d7fe598df94d12af9477db69aed2f12ab096464a; that is us!
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode d9865c86f89aa55ca0cd984cab1ca7e2b581259a 73.168.2.221:37335 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode dcb37497b0878541013b0a7de3a15f296d9e6f4f 73.168.2.221:53820 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode d6b0494f23abf02509b1de3b185afde071cda4d7 82.45.235.43:56617 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode c401b3f55206687eda7f816394a1c4111aff02eb 82.45.235.43:52879 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode ce9ac7747e93163a9c1c450d8faa3749496f3fc5 82.45.235.43:54735 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode fd0a6337596327d4953e4876070bf66b11d33714 82.45.235.43:57172 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode d075284ce79f859e75091a2d0323b70f0e6248be 82.45.235.43:50705 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode c6caf10b65f8193a39443094c74383e0008dca9e 82.45.235.43:52492 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode cd8e56c8de267fec0ba54ca4d195d01b8a2dc56e 50.1.232.3:35918 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode fa5286343da2cb7f50652f7a09a422df20932f77 82.45.235.43:57819 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode e883c39f42901f886ec336878b500d88455992af 82.45.235.43:56478 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode dcdae15336ab944c4a45c8d586c2ace7db7cdb2e 82.45.235.43:58892 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode db9fde2135b74a4db96092fe97fa610a0ffcc0bf 82.45.235.43:59452 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode ce1e99f5653e08f17733b2b37cf756b98d5d1781 73.168.2.221:6881 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode b05d46ffab4160614f2ecbe49fd5ccba4aa6463d 82.45.235.43:61191 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode 9bcec17e614ff04a7f20256237f1714ba901850d 82.45.235.43:6882 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode 98eea28601788e854e94479754b3f9eb3d5573af 82.45.235.43:6882 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode b966c91332578679cb99722810fda6c8dc917643 82.45.235.43:50447 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] addNode 9620fb55b2931c8b8af25c8f42b5a762d451c702 73.168.2.221:58470 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] got lookup response from e2d7c060225f930c31dc1bf7462ad09ac6ca466c
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 73.168.2.221:6881
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:59452
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:58892
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 73.168.2.221:58470
Sat, 30 May 2015 03:42:19 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:56478
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:57819
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 50.1.232.3:35918
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:52492
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:50705
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:50447
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:21 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:6882
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:57172
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:54735
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:52879
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:61191
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 82.45.235.43:56617
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:23 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 73.168.2.221:53820
Sat, 30 May 2015 03:42:25 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:25 GMT bittorrent-dht [d7fe598] sent find_node d7fe598df94d12af9477db69aed2f12ab096464a to 73.168.2.221:37335
Sat, 30 May 2015 03:42:25 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:25 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:25 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:25 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:25 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] terminating lookup (find_node) d7fe598df94d12af9477db69aed2f12ab096464a
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] K closest nodes are:
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   73.168.2.221:37335 d9865c86f89aa55ca0cd984cab1ca7e2b581259a
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   73.168.2.221:53820 dcb37497b0878541013b0a7de3a15f296d9e6f4f
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:56617 d6b0494f23abf02509b1de3b185afde071cda4d7
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:61191 b05d46ffab4160614f2ecbe49fd5ccba4aa6463d
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:52879 c401b3f55206687eda7f816394a1c4111aff02eb
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:54735 ce9ac7747e93163a9c1c450d8faa3749496f3fc5
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:57172 fd0a6337596327d4953e4876070bf66b11d33714
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:6882 9bcec17e614ff04a7f20256237f1714ba901850d
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:6882 98eea28601788e854e94479754b3f9eb3d5573af
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:50447 b966c91332578679cb99722810fda6c8dc917643
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:50705 d075284ce79f859e75091a2d0323b70f0e6248be
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:52492 c6caf10b65f8193a39443094c74383e0008dca9e
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   50.1.232.3:35918 cd8e56c8de267fec0ba54ca4d195d01b8a2dc56e
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:57819 fa5286343da2cb7f50652f7a09a422df20932f77
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   192.34.86.36:6881 e2d7c060225f930c31dc1bf7462ad09ac6ca466c
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:56478 e883c39f42901f886ec336878b500d88455992af
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   73.168.2.221:58470 9620fb55b2931c8b8af25c8f42b5a762d451c702
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:58892 dcdae15336ab944c4a45c8d586c2ace7db7cdb2e
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   82.45.235.43:59452 db9fde2135b74a4db96092fe97fa610a0ffcc0bf
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598]   73.168.2.221:6881 ce1e99f5653e08f17733b2b37cf756b98d5d1781
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] emit ready

Okay, we want to get: [32mef27491bdebe1026b1be58c295c8d1c9fe5f99c1[39m

Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] lookup (get_peers) ef27491bdebe1026b1be58c295c8d1c9fe5f99c1
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 73.168.2.221:58470
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:56478
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:59452
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:56617
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:54735
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 50.1.232.3:35918
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:50447
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:61191
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 73.168.2.221:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:52492
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:52879
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:58892
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:6882
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:57172
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:57819
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 73.168.2.221:53820
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 73.168.2.221:37335
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:50705
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 82.45.235.43:6882
Sat, 30 May 2015 03:42:27 GMT bittorrent-swarm new swarm (i ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 p 2d5757303031312d363864656230616238623831)
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode e2d7c060225f930c31dc1bf7462ad09ac6ca466c 192.34.86.36:6881 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode e883c39f42901f886ec336878b500d88455992af 82.45.235.43:56478 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode db9fde2135b74a4db96092fe97fa610a0ffcc0bf 82.45.235.43:59452 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode d6b0494f23abf02509b1de3b185afde071cda4d7 82.45.235.43:56617 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode ce9ac7747e93163a9c1c450d8faa3749496f3fc5 82.45.235.43:54735 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode cd8e56c8de267fec0ba54ca4d195d01b8a2dc56e 50.1.232.3:35918 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode ce1e99f5653e08f17733b2b37cf756b98d5d1781 73.168.2.221:6881 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode c6caf10b65f8193a39443094c74383e0008dca9e 82.45.235.43:52492 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode c401b3f55206687eda7f816394a1c4111aff02eb 82.45.235.43:52879 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode dcdae15336ab944c4a45c8d586c2ace7db7cdb2e 82.45.235.43:58892 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] skip addNode 73.168.2.221:41222 d7fe598df94d12af9477db69aed2f12ab096464a; that is us!
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode fd0a6337596327d4953e4876070bf66b11d33714 82.45.235.43:57172 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode fa5286343da2cb7f50652f7a09a422df20932f77 82.45.235.43:57819 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode dcb37497b0878541013b0a7de3a15f296d9e6f4f 73.168.2.221:53820 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode d9865c86f89aa55ca0cd984cab1ca7e2b581259a 73.168.2.221:37335 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode d075284ce79f859e75091a2d0323b70f0e6248be 82.45.235.43:50705 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode 81e24205d4bac8496d3e13282c90ead5045f09ea 127.0.0.1:6881 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode 9620fb55b2931c8b8af25c8f42b5a762d451c702 73.168.2.221:58470 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode b293437525bf23f70354c65f8bc4468987325554 122.172.203.144:62523 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode 9a250142b40eef2ce32e5ea73aa98fedb967bce6 104.236.212.110:6881 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] addNode b966c91332578679cb99722810fda6c8dc917643 82.45.235.43:50447 discovered from 192.34.86.36:6881
Sat, 30 May 2015 03:42:27 GMT bittorrent-dht [d7fe598] got lookup response from e2d7c060225f930c31dc1bf7462ad09ac6ca466c
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 104.236.212.110:6881
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 122.172.203.144:62523
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] sent get_peers ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 to 127.0.0.1:6881
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:29 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:31 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:31 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:31 GMT bittorrent-dht [d7fe598] got lookup error: query timed out
Sat, 30 May 2015 03:42:31 GMT bittorrent-dht [d7fe598] terminating lookup (get_peers) ef27491bdebe1026b1be58c295c8d1c9fe5f99c1
Sat, 30 May 2015 03:42:31 GMT bittorrent-dht [d7fe598] K closest nodes are:
Sat, 30 May 2015 03:42:31 GMT bittorrent-dht [d7fe598]   192.34.86.36:6881 e2d7c060225f930c31dc1bf7462ad09ac6ca466c
```

**Comment by viraptor** [comment]
Very similar result, but ending at:
```
  bittorrent-dht [7e30e20] terminating lookup (get_peers) ef27491bdebe1026b1be58c295c8d1c9fe5f99c1 +1ms
  bittorrent-dht [7e30e20] K closest nodes are: +0ms
  bittorrent-dht [7e30e20]   192.34.86.36:6881 9130b8ef1c30ef269b014f3f0229123154673bcc +0ms
  bittorrent-dht [7e30e20]   104.236.212.110:6881 5bd26e8f70cab61951fe22e0c2c419ebc175f153 +0ms
  bittorrent-dht [7e30e20] addNode 76076dcf73c94815e3760d01a548cf1388a0e267 82.45.235.43:56384 discovered from 82.45.235.43:56384 +739ms
  bittorrent-dht [7e30e20] got find_node 76076dcf73c94815e3760d01a548cf1388a0e267 from 82.45.235.43:56384 +1ms
```
No more messages afterwards.

npm 2.10.0
nodejs 0.12.3
git 2.4.1
gittorrent 0.1.5

**Comment by philip-wernersbach** [comment]
Clone hangs here too. Gist at https://gist.github.com/philip-wernersbach/24e1f3bab529271240be. I let it run for about five minutes after it hung before I killed it.

OS X Yosemite
nodejs 0.12.2
git 2.4.0
gittorrent 0.1.7

**Comment by cjb** [comment]
@philip-wernersbach What are you trying to clone?  I think the problem for you might just be that the thing you're cloning isn't being seeded, and #5 isn't done yet for a fallback.

**Comment by philip-wernersbach** [comment]
I'm trying to clone this repository.

**Comment by cjb** [comment]
@philip-wernersbach Could you try again, and let me know what hash you see for "Okay, we need to get: .."?  I think the problem is that I just pushed out an update without also seeding it.

**Comment by philip-wernersbach** [comment]
It's getting ec9f63e828de47aeb15c28b7a4ebacee71770276. I just tried and was able to download it, so the problem was seeding.

**Comment by whit2333** [comment]
It's getting a connection now, but still hangs:
The tail of the output is

```bash
  bittorrent-swarm:peer new Peer 10.20.30.3:30000 +999ms
  bittorrent-swarm _drain numConns 1 maxConns 55 +0ms
  bittorrent-swarm drain (1 queued, 0/55 peers) +1ms
  bittorrent-swarm tcp connect attempt to 10.20.30.3:30000 +0ms
  bittorrent-swarm drain (1 queued, 0/55 peers) +15s
  bittorrent-swarm tcp connect attempt to 127.0.0.1:38677 +1ms
  bittorrent-swarm drain (0 queued, 0/55 peers) +1ms
  bittorrent-swarm:peer destroy Peer 10.20.30.3:30000 (error: connect timeout) +25s
  bittorrent-swarm _drain numConns 1 maxConns 55 +0ms
  bittorrent-swarm drain (0 queued, 0/55 peers) +0ms
  bittorrent-swarm conn 10.20.30.3:30000 closed: will re-add to queue in 5000ms (attempt 2) +0ms
  bittorrent-swarm:peer new Peer 10.20.30.3:30000 +5s
  bittorrent-swarm _drain numConns 1 maxConns 55 +0ms
  bittorrent-swarm drain (1 queued, 0/55 peers) +0ms
  bittorrent-swarm tcp connect attempt to 10.20.30.3:30000 +1ms
  bittorrent-swarm drain (1 queued, 0/55 peers) +30s
  bittorrent-swarm tcp connect attempt to 127.0.0.1:38677 +0ms
  bittorrent-swarm drain (0 queued, 0/55 peers) +1ms
  bittorrent-swarm:peer destroy Peer 10.20.30.3:30000 (error: connect timeout) +25s
  bittorrent-swarm _drain numConns 1 maxConns 55 +0ms
  bittorrent-swarm drain (0 queued, 0/55 peers) +0ms
  bittorrent-swarm conn 10.20.30.3:30000 closed: will re-add to queue in 15000ms (attempt 3) +1ms
  bittorrent-swarm:peer new Peer 10.20.30.3:30000 +15s
  bittorrent-swarm _drain numConns 1 maxConns 55 +0ms
  bittorrent-swarm drain (1 queued, 0/55 peers) +0ms
  bittorrent-swarm tcp connect attempt to 10.20.30.3:30000 +0ms
  bittorrent-swarm:peer destroy Peer 10.20.30.3:30000 (error: connect timeout) +25s
  bittorrent-swarm _drain numConns 1 maxConns 55 +0ms
  bittorrent-swarm drain (0 queued, 0/55 peers) +0ms
  bittorrent-swarm conn 10.20.30.3:30000 closed: will not re-add (max 3 attempts) +0ms
  bittorrent-swarm drain (1 queued, 0/55 peers) +1m
  bittorrent-swarm tcp connect attempt to 127.0.0.1:38677 +0ms
  bittorrent-swarm drain (0 queued, 0/55 peers) +0ms
  bittorrent-swarm drain (1 queued, 0/55 peers) +2m
  bittorrent-swarm tcp connect attempt to 127.0.0.1:38677 +0ms
  bittorrent-swarm drain (0 queued, 0/55 peers) +1ms
```

**Comment by cjb** [comment]
@whit2333 Is it possible that you're behind a NAT that doesn't allow BitTorrent or something?

**Comment by frankier** [comment]
I have the same problem. I am behind a NAT (Saunalahti 3G modem). A normal bittorrent client does work for me, including DHT. WebTorrent seems to download a trackerless torrent, but seems to me (without doing a proper test) to take a little longer to get started compared to Transmission (it does get a lot of peers though). Perhaps a first step to figuring out what's going wrong could be to add some trace to ut_gittorrent?

Also it seems from a first read of the code + using Wireshark that get_peers is only sent once. (Although it looks like keepalives are sent every couple of minutes.) Perhaps any NAT udp connection tracking wonkyness could be mitigated by retrying a few times?

**Comment by cjb** [comment]
@frankier Thanks.  Issue #5 will handle sending multiple get_peers().  Happy to get tracing added to `ut_gittorrent` if `DEBUG=*` isn't catching it.
